### ISSUE TITLE
execute_plan是否为有主函数入口？如果是，plan_id这个参数如何取得呢，需要我们再额外增加代码对问题所对应的plan_id进行分类吗？

### ISSUE THREAD

**Issue by cj-wade** [hehaha68/law_glm_baseline#1]
代码倒是写的不复杂，但是看的稍微有点懵，特来请教一下。感谢回复！

**Comment by cj-wade** [comment]
即，无法直接跑通？

**Comment by hehaha68** [comment]
> 代码倒是写的不复杂，但是看的稍微有点懵，特来请教一下。感谢回复！

sub.py是主函数～，execute_plan执行一个问题的plan

**Comment by cj-wade** [comment]
原来sub是submission的意思，我搞错了以为是处理子问题的文件，就没仔细看。感谢！
