### ISSUE TITLE
closed

### ISSUE THREAD

**Issue by Maekfei** [hehaha68/law_glm_baseline#2]

**Comment by hehaha68** [comment]
检查一下生成的文件看看内容？
是不是api key和team id没有填写呀

**Comment by Maekfei** [comment]
api和team id 都填了 答案看着也挺正常的 不知道评测怎么只有25分
[submission.json](https://github.com/user-attachments/files/15972155/submission.json)

**Comment by Maekfei** [comment]
> 检查一下生成的文件看看内容？ 是不是api key和team id没有填写呀

api和team id 都填了 答案看着也挺正常的 不知道评测怎么只有25分
[submission.json](https://github.com/user-attachments/files/15972329/submission.json)

**Comment by hehaha68** [comment]
> api和team id 都填了 答案看着也挺正常的 不知道评测怎么只有25分 [submission.json](https://github.com/user-attachments/files/15972155/submission.json)

我看了一下，和我这里的submission还不太一样，我检查一下代码的改动哈，明天给你答复

**Comment by Maekfei** [comment]
谢谢🙏

---- 回复的原邮件 ----
| 发件人 | Yorick ***@***.***> |
| 发送日期 | 2024年06月25日 21:54 |
| 收件人 | hehaha68/law_glm_baseline ***@***.***> |
| 抄送人 | LuMF ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [hehaha68/law_glm_baseline] 请问大佬为什么代码原封不动跑一遍提交评测只有25分，是答案中有什么特殊字符需要额外处理吗？ (Issue #2) |

api和team id 都填了 答案看着也挺正常的 不知道评测怎么只有25分 submission.json

我看了一下，和我这里的submission还不太一样，我检查一下代码的改动哈，明天给你答复

**Comment by hehaha68** [comment]
> 谢谢🙏
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | Yorick ***@***.***> | | 发送日期 | 2024年06月25日 21:54 | | 收件人 | hehaha68/law_glm_baseline ***@***.***> | | 抄送人 | LuMF ***@***.***>, Author ***@***.***> | | 主题 | Re: [hehaha68/law_glm_baseline] 请问大佬为什么代码原封不动跑一遍提交评测只有25分，是答案中有什么特殊字符需要额外处理吗？ (Issue #2) | api和team id 都填了 答案看着也挺正常的 不知道评测怎么只有25分 submission.json 我看了一下，和我这里的submission还不太一样，我检查一下代码的改动哈，明天给你答复 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

你可以单独检查测试一下qid从79开始的一些问题，我看这个submission里面从79开始的所有问题都没有回答哎，是不是api key上限了。

**Comment by Maekfei** [comment]
> > 谢谢🙏
> > […](#)
> > ---- 回复的原邮件 ---- | 发件人 | Yorick _**@**_._**> | | 发送日期 | 2024年06月25日 21:54 | | 收件人 | hehaha68/law_glm_baseline _**@**_.**_> | | 抄送人 | LuMF _**@**_._**>, Author _**@**_.**_> | | 主题 | Re: [hehaha68/law_glm_baseline] 请问大佬为什么代码原封不动跑一遍提交评测只有25分，是答案中有什么特殊字符需要额外处理吗？ (Issue #2) | api和team id 都填了 答案看着也挺正常的 不知道评测怎么只有25分 submission.json 我看了一下，和我这里的submission还不太一样，我检查一下代码的改动哈，明天给你答复 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: _**@**_.***>
> 
> 你可以单独检查测试一下qid从79开始的一些问题，我看这个submission里面从79开始的所有问题都没有回答哎，是不是api key上限了。

啊 好的 谢谢
